# Generated by Django 5.0.1 on 2024-05-28 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparado', '0004_alter_categoria_nombre_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre_cat',
            field=models.CharField(max_length=100),
        ),
    ]
