# Generated by Django 5.0.1 on 2024-06-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparado', '0006_rename_id_solicitud_comentario_solicitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='categorias',
            field=models.ManyToManyField(blank=True, to='reparado.categoria'),
        ),
    ]
