# Generated by Django 5.0.1 on 2024-06-03 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparado', '0007_usuario_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='solicitudes_tecnico', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='solicitudes_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
