# Generated by Django 5.0.1 on 2024-06-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparado', '0008_solicitud_tecnico_alter_solicitud_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='tiempo_estimado',
            field=models.IntegerField(default=120),
        ),
    ]
