# Generated by Django 5.0.1 on 2024-06-17 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparado', '0009_servicio_tiempo_estimado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='tiempo_estimado',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='tiempo_estimado',
            field=models.IntegerField(default=120),
        ),
    ]
