# Generated by Django 5.0.1 on 2024-06-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparado', '0010_remove_servicio_tiempo_estimado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='tiempo_estimado',
            field=models.IntegerField(default=120),
        ),
    ]
