# Generated by Django 5.0.1 on 2024-09-21 12:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparado', '0014_alter_factura_metodo_pago_factura_forma_pago_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={'verbose_name_plural': 'Servicio'},
        ),
        migrations.AlterModelOptions(
            name='solicitud',
            options={'verbose_name_plural': 'Solicitud'},
        ),
        migrations.AddField(
            model_name='servicio',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
