# Generated by Django 5.0.1 on 2024-09-16 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reparado', '0014_alter_factura_metodo_pago_factura_forma_pago_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={'verbose_name_plural': 'Servicio'},
        ),
        migrations.AlterModelOptions(
            name='solicitud',
            options={'verbose_name_plural': 'Solicitud'},
        ),
    ]
