# Generated by Django 5.0.1 on 2024-09-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparado', '0016_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Administrador'), ('TEC', 'Técnico'), ('CLI', 'Cliente')], default='USU', max_length=5, null=True),
        ),
    ]
