# Generated by Django 5.0.1 on 2024-09-17 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparado', '0017_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitud',
            options={'verbose_name_plural': 'Solicitudes'},
        ),
        migrations.AlterField(
            model_name='compra',
            name='estado',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Creado'), (2, 'Enviado'), (3, 'Cancelado')], default=1),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='tecnico',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'TEC'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='solicitudes_tecnico', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
