# Generated by Django 5.0.1 on 2024-09-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparado', '0018_alter_solicitud_options_alter_compra_estado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'verbose_name_plural': 'Compra'},
        ),
        migrations.AlterModelOptions(
            name='factura',
            options={'verbose_name_plural': 'Factura'},
        ),
        migrations.AlterModelOptions(
            name='solicitud',
            options={'verbose_name_plural': 'Solicitud'},
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Administrador'), ('TEC', 'Técnico'), ('CLI', 'Cliente')], default='CLI', max_length=5, null=True),
        ),
    ]
