# Generated by Django 5.0.1 on 2024-09-21 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparado', '0019_alter_compra_options_alter_factura_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={},
        ),
        migrations.AlterModelOptions(
            name='factura',
            options={},
        ),
        migrations.AlterField(
            model_name='compra',
            name='estado',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Creado'), (2, 'Enviado'), (3, 'Cancelado'), (4, 'Completado')], default=1),
        ),
        migrations.AlterField(
            model_name='factura',
            name='compra',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reparado.compra'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='forma_pago',
            field=models.CharField(choices=[('CONTADO', 'Pago al contado'), ('CREDITO', 'Pago mediante crédito')], default='CONTADO', max_length=50),
        ),
        migrations.AlterField(
            model_name='factura',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA_CREDITO', 'Tarjeta de crédito')], default='EFECTIVO', max_length=50),
        ),
    ]
