# Generated by Django 5.0.1 on 2024-05-09 17:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Auditoría',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cat', models.CharField(max_length=100)),
                ('desc', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Categoría',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField()),
                ('total', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Factura',
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_Metodo', models.CharField(max_length=200)),
                ('desc_metodo', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Metodo Pago',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nombre', models.CharField(max_length=254)),
                ('apellido', models.CharField(max_length=254)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=254)),
                ('password', models.CharField(max_length=254)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('foto', models.ImageField(default='usuarios/default.png', upload_to='usuarios/')),
                ('token', models.CharField(blank=True, max_length=10, null=True)),
                ('rol', models.CharField(blank=True, choices=[('ADMIN', 'Administrador'), ('SEC', 'Secretaria'), ('TEC', 'Técnico'), ('USU', 'Usuario')], default='USU', max_length=5, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.IntegerField(blank=True, choices=[(1, 'Creado'), (2, 'Enviado'), (3, 'Cancelado')], default=1)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Compra',
            },
        ),
        migrations.CreateModel(
            name='FacturaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('monto', models.IntegerField()),
                ('id_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparado.factura')),
                ('id_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparado.metodopago')),
            ],
            options={
                'verbose_name_plural': 'Factura Pago',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ser', models.CharField(max_length=200)),
                ('desc_ser', models.TextField()),
                ('precio', models.IntegerField()),
                ('foto', models.ImageField(default='productos/default.png', upload_to='productos/')),
                ('id_categorias', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reparado.categoria')),
            ],
            options={
                'verbose_name_plural': 'Servicio',
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField()),
                ('id_compra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reparado.compra')),
                ('id_servicio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reparado.servicio')),
            ],
            options={
                'verbose_name_plural': 'Detalle Compra',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('precio', models.IntegerField()),
                ('zona', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('NO_DISPONIBLE_TEMPORALMENTE', 'No disponible temporalmente'), ('EN_ESPERA', 'En espera'), ('EN_PROGRESO', 'En progreso'), ('COMPLETADO', 'Completado'), ('CANCELADO_PROVEEDOR', 'Cancelado por el proveedor'), ('CANCELADO_USUARIO', 'Cancelado por el usuario'), ('EN_REVISION', 'En revisión'), ('PROGRAMADO', 'Programado'), ('EN_ESPERA_PAGO', 'En espera de pago')], default='DISPONIBLE', max_length=50)),
                ('id_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparado.servicio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Solicitud',
            },
        ),
        migrations.AddField(
            model_name='factura',
            name='id_solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reparado.solicitud'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=200)),
                ('comentario', models.CharField(max_length=254)),
                ('estrellas', models.IntegerField()),
                ('id_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparado.solicitud')),
            ],
            options={
                'verbose_name_plural': 'Comentario',
            },
        ),
    ]
