# Generated by Django 5.0.1 on 2024-06-03 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reparado', '0005_alter_categoria_nombre_cat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='id_solicitud',
            new_name='solicitud',
        ),
        migrations.RenameField(
            model_name='detallecompra',
            old_name='id_compra',
            new_name='compra',
        ),
        migrations.RenameField(
            model_name='detallecompra',
            old_name='id_servicio',
            new_name='servicio',
        ),
        migrations.RenameField(
            model_name='factura',
            old_name='id_solicitud',
            new_name='solicitud',
        ),
        migrations.RenameField(
            model_name='facturapago',
            old_name='id_factura',
            new_name='factura',
        ),
        migrations.RenameField(
            model_name='facturapago',
            old_name='id_pago',
            new_name='pago',
        ),
        migrations.RenameField(
            model_name='servicio',
            old_name='id_categorias',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='solicitud',
            old_name='id_servicio',
            new_name='servicio',
        ),
    ]
