# Generated by Django 5.0.1 on 2024-07-07 17:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparado', '0012_alter_servicio_options_alter_solicitud_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Auditoria',
        ),
        migrations.RemoveField(
            model_name='facturapago',
            name='factura',
        ),
        migrations.RemoveField(
            model_name='facturapago',
            name='pago',
        ),
        migrations.AlterModelOptions(
            name='compra',
            options={'verbose_name_plural': 'Compras'},
        ),
        migrations.AlterModelOptions(
            name='factura',
            options={'verbose_name_plural': 'Facturas'},
        ),
        migrations.AlterModelOptions(
            name='metodopago',
            options={'verbose_name_plural': 'Metodos de Pago'},
        ),
        migrations.RenameField(
            model_name='metodopago',
            old_name='nombre_Metodo',
            new_name='nombre_metodo',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='solicitud',
        ),
        migrations.AddField(
            model_name='factura',
            name='compra',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='reparado.compra'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura',
            name='fecha_pago',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='factura',
            name='metodo_pago',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='reparado.metodopago'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_emision',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('EN_ESPERA', 'En espera'), ('EN_PROGRESO', 'En progreso'), ('COMPLETADO', 'Completado'), ('CANCELADO_PROVEEDOR', 'Cancelado por el proveedor'), ('CANCELADO_USUARIO', 'Cancelado por el usuario'), ('PROGRAMADO', 'Programado')], default='EN_ESPERA', max_length=50),
        ),
        migrations.DeleteModel(
            name='DetalleCompra',
        ),
        migrations.DeleteModel(
            name='FacturaPago',
        ),
    ]
