# Generated by Django 5.0.1 on 2024-10-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparado', '0024_alter_usuario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='servicios',
            field=models.ManyToManyField(blank=True, related_name='compras', to='reparado.servicio'),
        ),
    ]
