# Generated by Django 5.0.1 on 2024-10-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparado', '0025_compra_servicios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='servicios',
            field=models.ManyToManyField(related_name='compras', to='reparado.servicio'),
        ),
    ]
