# Generated by Django 5.0.1 on 2024-10-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparado', '0026_alter_compra_servicios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='servicios',
        ),
        migrations.AddField(
            model_name='factura',
            name='servicios',
            field=models.ManyToManyField(to='reparado.servicio'),
        ),
    ]
