# Generated by Django 5.0.1 on 2024-10-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparado', '0029_remove_compra_servicios_factura_servicios'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='servicios',
            field=models.ManyToManyField(to='reparado.servicio'),
        ),
    ]
