# Generated by Django 5.0.1 on 2024-10-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparado', '0030_compra_servicios'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='compra',
            field=models.ManyToManyField(to='reparado.compra'),
        ),
    ]
